### ISSUE TITLE
MiniPerplx does not work anymore?

### ISSUE THREAD

**Issue by JuliXBR4VO** [zaidmukaddam/miniperplx#11]
Everytime i try to search something this error ocurre….
You can See ist in the Screenshot.
![IMG_1344](https://github.com/user-attachments/assets/615ba9a7-c180-48c4-b70f-0b237c0daf89)

**Comment by zaidmukaddam** [comment]
hey! sorry for the inconvenience, I am out of funds and credits to keep the models running.
