### ISSUE TITLE
Compliments and feature request

### ISSUE THREAD

**Issue by sans202** [zaidmukaddam/miniperplx#15]
Hello! I Just wanted to let you know the project looks great so far! I really like the UI!:D

Could you add specific searches? For example search only on Wikipedia, on Reddit, on academic sources?

**Comment by zaidmukaddam** [comment]
Hey! Thanks for the kind words and the great suggestion! I’ll look into adding specific searches like Wikipedia, Reddit, or academic sources. Stay tuned!

**Comment by sans202** [comment]
thank you for adding those!
