### ISSUE TITLE
Issue: Autoscrolling on response

### ISSUE THREAD

**Issue by waleedlatif1** [zaidmukaddam/miniperplx#17]
When the response is being streamed, the page autoscrolls to the bottom. If the user tries to scroll up, the page position automatically goes back to the new text/content being streamed. This page position hijack doesn't make for a good user experience.

**Comment by zaidmukaddam** [comment]
It is because of this:

```js
useEffect(() => {
    if (bottomRef.current) {
        bottomRef.current.scrollIntoView({ behavior: "smooth" });
    }
}, [messages, suggestedQuestions]);
```

[app/search/page.tsx#2033](https://github.com/zaidmukaddam/miniperplx/blob/296a8369ca855f5e3283d5f69dca08488ef9f374/app/search/page.tsx#L2033C5-L2037C40)

**Comment by zaidmukaddam** [comment]
This fix seems to be working well! thank you for contributing @waleedlatif1! awesome work!

I will be closing this issue now. reopen if you want to.
