### ISSUE TITLE
there is no way to edit the question . 

### ISSUE THREAD

**Issue by hemangjoshi37a** [zaidmukaddam/miniperplx#2]
there is no way to edit the question . can you please add some way to edit the asked question and resend ?

**Comment by zaidmukaddam** [comment]
<img width="738" alt="Screenshot 2024-08-13 at 6 15 59 PM" src="https://github.com/user-attachments/assets/2301504d-3797-43b6-a7af-6efbfd35c208">

Once the response is completed you can send a new question from the input bar in the bottom. Check image.

**Comment by hemangjoshi37a** [comment]
I don't want to send new request but I want to edit and submit the original one.

**Comment by zaidmukaddam** [comment]
I have added the edit query option now. Check commit: [#28](https://github.com/zaidmukaddam/miniperplx/commit/e4713715453636bf329ee8474362662765151d09)
