### ISSUE TITLE
Feature: Flight widget

### ISSUE THREAD

**Issue by waleedlatif1** [zaidmukaddam/miniperplx#22]
If someone types in Emirates Airlines Flight EK210 and this appears, I think it would be pretty neat. This is not even something pplx.ai does yet, and could be a super cool feature to add on. 

<img width="683" alt="Screenshot 2024-12-17 at 4 15 47 PM" src="https://github.com/user-attachments/assets/d7fce9c7-b24d-4815-b115-097055298a0c" />

The implementation of this would be something similar to what we currently have for weather, but for flights instead.

**Comment by zaidmukaddam** [comment]
Yeah it will be a good integration to add!
