### ISSUE TITLE
Readability: Improve AI response's readability

### ISSUE THREAD

**Issue by huytd** [zaidmukaddam/miniperplx#33]
Currently, MiniPerplx provide an answer in a plain, multi-paragraph style, which might not great in term of readability, for example, with the following question:

<img width="767" alt="image" src="https://github.com/user-attachments/assets/fbe2ab34-0bd7-4290-82c5-c7c5c2e6e487" />

This is the default AI's response:

<img width="755" alt="image" src="https://github.com/user-attachments/assets/b2ea8f46-9aea-4c8c-b14e-0c7767a16f4b" />

With a little tweak in the prompt, we can have a more structured answer that is easier to read:

<img width="778" alt="image" src="https://github.com/user-attachments/assets/5962cb34-de3c-4f57-a689-6c0193071b43" />

The answer:

<img width="765" alt="image" src="https://github.com/user-attachments/assets/1ea0e5ac-d01b-4543-a217-1f9e8646bf0a" />

Maybe we can improve the system prompt, or give the user an ability to customize the prompt to support this?

After a few tries, it seems like this additional prompt can provide a good answer:

```
give a structured answer with headings for each section.
try to use bullet points instead of just a plain paragraph.
put citation after each bullet point instead of at the end of the whole anser.
```

**Comment by zaidmukaddam** [comment]
Hey Huy! Thanks for pointing that out! Will make that change for sure!

**Comment by zaidmukaddam** [comment]
The new system instruction is live now! Check it out! Let me know if there is anything else. Closing this issue now.

**Comment by huytd** [comment]
That’s awesome! Thank you so much!!!
