### ISSUE TITLE
Question box expands and hides previous result

### ISSUE THREAD

**Issue by rikhardt** [zaidmukaddam/miniperplx#34]
While using the application, I've noticed that the question box expands unexpectedly, preventing the previous result from being visible.

Attached is a screenshot showing how the question box expands and hides the previous result.
![image](https://github.com/user-attachments/assets/372d7f6b-9959-4bd1-96b0-4178f27f3c20)

**Comment by zaidmukaddam** [comment]
Hey! I noticed the issue! It has now been fixed!

**Comment by rikhardt** [comment]
Hey! Thanks for fixing the issue so quickly
