### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by Pratham271** [zaidmukaddam/miniperplx#7]
@zaidmukaddam how about we add image support from tavily during web search similar to searchgpt. It will make the ui look more premium, I can raise a pr as I have already done it.
<img width="1710" alt="Screenshot 2024-08-28 at 6 05 45 AM" src="https://github.com/user-attachments/assets/9c156212-bd4a-412f-aa54-44088911d887">

**Comment by zaidmukaddam** [comment]
Hey Pratham, raise a pull request. I'll check it out and merge it if it looks good!

**Comment by zaidmukaddam** [comment]
Hey Pratham, the repo is currentlynot  up to date with the live site. I will make the changes from my end, does that work for you?

**Comment by Pratham271** [comment]
yeah but I don't get why is this not upto date. I mean what's the issue

**Comment by Pratham271** [comment]
I have few more features in mind let me test it

**Comment by zaidmukaddam** [comment]
Hey! I have pushed a new commit! The main app is now shifted to `app/search` directory!
